namespace MSKit.UIView
{
	public enum Views
	{
		MainMenu = 0,
		LevelComplete = 1,
		LevelFail = 2,
		GameplayHud = 3,
		ItemProgressView = 4,
		LevelPause = 5,
		Settings = 6,
		ItemProgressPopUp = 7,
		RestartPopup = 8,
		Loading = 9,
		BlockerView = 10,
		LeaderBoard = 11,
		RevivePopUp = 12,
		PowerUpsSpinner = 13,
		ButterflySpinner = 14,
		BoosterView = 15,
		Transition = 16,
		FlowerUnlockView = 17,
		Market = 18,
		SkipitOffer = 19,
		AdLoading = 20,
		SpecialOffer = 22,
		ItemUpgradeMenu = 23,
		PowerUpSelectionView = 24,
		GameMenu = 25,
		StarsNotEnoughView = 26,
		CardCollectionView = 27,
		StarterPack = 28,
		OutOfSkipAds = 29,
		CheckPointComplete = 30,
		CardsOffer = 31,
		SkipAdsOffer = 32,
		ItemUpgradeInfoView = 33,
		SeasonalProgressPassView = 34,
		Floater = 35,
		UpdateGameDialogue = 36,
		MissionCenterView = 37,
		BloomPassPurchaseView = 38,
		LiveOpsOffer = 39,
		RemoveAdsFSO = 40,
		EventIntroView = 41
	}
}
